Use (and pass) Clang's `-Wbad-function-cast` check and enable in CI
aremmell/libsir pull request #227
Opened 2023-08-22 12:43 UTC by johnsonjh

* Use (and pass) Clang's `-Wbad-function-cast` check and enable in CI

2023-08-23 11:17 UTC, aremmell approved these changes

2023-08-23 11:18 UTC, aremmell commented
I forgot about the LAN address in the script... need to fix that before we pres butan 2 merge

2023-08-23 12:10 UTC, aremmell requested changes
Just need to get rid of the LAN IP in Dockerfile...

2023-08-23 12:56 UTC, johnsonjh commented on Makefile
> +	$(CC) -o $(OUT_TESTS) $(OBJ_TESTS) -Iinclude $(LIBSIR_S) $(LDFLAGS) -lm
It's for lroundf - and we don't want to link the math library for everything - only for sirtests

2023-08-23 13:36 UTC, johnsonjh commented on Makefile
> +	$(CC) -o $(OUT_TESTS) $(OBJ_TESTS) -Iinclude $(LIBSIR_S) $(LDFLAGS) -lm
Also, it's only needed for Unix - it's just in libc in windows, so no changes needed.

2023-08-23 15:43 UTC, johnsonjh commented
> Just need to get rid of the LAN IP in Dockerfile...

@aremmell It's correct, but I added an argument so you can override locally without editing via `--build-arg URL="..."`

2023-08-23 21:49 UTC, aremmell commented
Erm, isn't the pluginexport just a typedef void*?

2023-08-24 02:14 UTC, johnsonjh commented
> Erm, isn't the pluginexport just a typedef void*?

Seems to be. MSVC doesn't like it.

2023-08-24 07:23 UTC, aremmell commented
> > Erm, isn't the pluginexport just a typedef void*?
> 
> Seems to be. MSVC doesn't like it.

It's because on Windows, it's typedef FARPROC.

2023-08-24 12:31 UTC, johnsonjh commented
> > > Erm, isn't the pluginexport just a typedef void*?
> > 
> > 
> > Seems to be. MSVC doesn't like it.
> 
> It's because on Windows, it's typedef FARPROC.

Well Windows sucks for being weird.

2023-08-24 14:29 UTC, aremmell approved these changes

2023-08-24 14:49 UTC, merged